language: python

# you can use a different version of Python
python: "3.6"

# don't clone more than necessary
git:
  depth: 1

# Install dependencies
install:
  - pip install -r requirements.txt

before_script:
   - echo "DEBUG = False" >> .env
   - echo "SECRET_KEY = secretkeys" >> .env

# script to run tests. Script can have many commands, one per line.
script:
  - coverage run -m unittest discover -p "*_tests.py"

after_script:
  - bash <(curl -s https://codecov.io/bash)