# Generated by Django 3.2.7 on 2021-09-11 18:54
"""Updates question and end date for database."""
from django.db import migrations, models


class Migration(migrations.Migration):
    """Make migration for question and end date."""

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(null=True,
                                       verbose_name='ending date'),
        ),
    ]
